### ISSUE TITLE
在部分地图保存状态会导致游戏崩溃

### ISSUE THREAD

**Issue by WEGFan** [DemoJameson/CelesteSpeedrunTool#2]
只试了第一章A面9、9b、9z和B面的01

```
Ver 1.3.1.2 [Everest: 1312-azure-6138f]
01/08/2020 16:35:41
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.TryGetValue(TKey key, TValue& value)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValue(TKey key, CreateValueCallback createValueCallback)
   at Celeste.Mod.SpeedrunTool.Extensions.CommonExtensions.GetExtendedDataValue[T](Object o, String name)
   at Celeste.Mod.SpeedrunTool.SaveLoad.Actions.StaticMoverAction.CheckIfNotAttachStaticMover(Boolean shouldNotAttach, StaticMover staticMover, Platform platform)
   at MonoMod.Cil.RuntimeILReferenceBag.FastDelegateInvokers.Invoke[T1,T2,T3,TResult](T1 arg1, T2 arg2, T3 arg3, Func`4 del)
   at DMD<Celeste.Solid::Awake>(Solid , Scene )
   at Monocle.EntityList.UpdateLists()
   at Monocle.Scene.BeforeUpdate()
   at DMD<Monocle.Engine::Update>(Engine , GameTime )
   at Celeste.Mod.SpeedrunTool.SpeedrunToolModule.RespawnSpeed(orig_Update orig, Engine self, GameTime time)
   at DMD<DMD<Hook<Monocle.Engine::Update>?47080266>?21069217::Hook<Monocle.Engine::Update>?47080266>(Engine , GameTime )
   at Celeste.Celeste.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.RunLoop(Game game)
   at Microsoft.Xna.Framework.Game.Run()
   at Monocle.Engine.RunWithLogging() in d:\a\1\s\Celeste.Mod.mm\Patches\Monocle\Engine.cs:line 29
```

**Comment by DemoJameson** [comment]
你用的什么版本，GameBanana 上的最新版应该已经修复这个 Bug 了

**Comment by WEGFan** [comment]
下载的是 speedruntool_v1629.zip 这个文件，但是 everest.yaml 里写的是 1.6.28

**Comment by DemoJameson** [comment]
看来是我上传错文件了 =_=
我已经再次更新了，你下载测试一下

**Comment by WEGFan** [comment]
还是会崩溃

**Comment by DemoJameson** [comment]
麻烦你上传一下游戏目录的 log.txt 我看看是什么原因

**Comment by WEGFan** [comment]
[log.txt](https://github.com/DemoJameson/CelesteSpeedrunTool/files/4034546/log.txt)

**Comment by DemoJameson** [comment]
[SpeedrunTool_v1.6.32.zip](https://github.com/DemoJameson/CelesteSpeedrunTool/files/4034648/SpeedrunTool_v1.6.32.zip)
看起来是上次修复刺依附到错误单位这个 BUG 的写法在你的电脑上水土不服了，我换一种写法你试试

**Comment by WEGFan** [comment]
可以了，谢谢
