### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ghosty920** [DemoJameson/CelesteSpeedrunTool#32]
```
Celeste Error Log
==========================================

Ver 1.4.0.0-fna [Everest: 4465-azure-52f83]
01/22/2024 17:47:15
System.Exception: FMOD Failed: ERR_OUTPUT_INIT (Error initializing output device.)
   at Celeste.Audio.CheckFmod(RESULT result) in /home/vsts/work/1/s/Celeste.Mod.mm/Patches/Audio.cs:line 42
   at DMD<System.Void Celeste.Audio:Init()>()
   at Celeste.Mod.SpeedrunTool.Other.MuteInBackground.AudioOnInit(orig_Init orig)
   at Hook<System.Void Celeste.Mod.SpeedrunTool.Other.MuteInBackground::AudioOnInit(On.Celeste.Audio+orig_Init)>()
   at SyncProxy<System.Void Celeste.Audio:Init()>()
   at Celeste.GameLoader.LoadThread()
   at Celeste.RunThread.RunThreadWithLogging(Action method)

```

I have Mute in Background enabled
My game window wasn't even opened yet, I just opened my game
My mouse was focused on discord (not epic, not the desktop...)

Edit: restarted my game, crashed. I was focused on the window (that appeared) this time

Edit2: Went on youtube rq and got this error "Audio renderer error", do whatever u want of this issue ig now

**Comment by DemoJameson** [comment]
not a speedruntool bug

> Something went wrong with the sound engine used by Celeste.
>
> Possible fixes are: 
> Unplug/replug your speakers/headphones
> Try a different set of speakers/headphones
> Restart your audio drivers/your PC
> Update your audio drivers
>
> This can also sometimes be triggered by connecting a new audio device.
